language: java
sudo: false

branches:
  only:
  - master

os: linux

cache:
  directories:
  - lib
  - $HOME/.m2

jdk:
- oraclejdk8
- openjdk7

script:
- ant
- ant report
- if [ -f jacoco/report.xml ] ; then mvn exec:java ; fi
